version: '3'

volumes:
  expenses_local_postgres_data: {}
  expenses_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: expenses_local_django
    container_name: expenses_local_django
    depends_on:
      - postgres
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: expenses_production_postgres
    container_name: expenses_local_postgres
    volumes:
      - expenses_local_postgres_data:/var/lib/postgresql/data
      - expenses_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: expenses_local_docs
    container_name: expenses_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./expenses:/app/expenses:z
    ports:
      - '9000:9000'
    command: /start-docs

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: expenses_local_mailpit
    ports:
      - "8025:8025"
